- name: Create Glue security group
  amazon.aws.ec2_security_group:
    name: glue-sg
    vpc_id: "{{ vpc_id }}"
    description: Glue access
    region: "{{ region }}"
  register: glue_sg

- name: Create RDS security group
  amazon.aws.ec2_security_group:
    name: rds-sg
    vpc_id: "{{ vpc_id }}"
    description: RDS access
    region: "{{ region }}"
    rules:
      - proto: tcp
        from_port: "{{ db_port }}"
        to_port: "{{ db_port }}"
        group_id: 
          - "{{ glue_sg.group_id }}"
  register: rds_sg
