name: Deploy CpeLoad Infrastructure

on:
  workflow_run:
    workflows: ["Build CpeLoad Image"]
    types: [completed]

env:
  AWS_REGION: us-gov-west-1

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
      actions: read   # needed to download artifacts

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_GOVCLOUD_ROLE_ARN }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts

      - name: Load ECR URI + Image Tag
        run: |
          export ECR_URI=$(cut -d '=' -f2 ecr.txt)
          export IMAGE_TAG=$(cut -d '=' -f2 image.txt)
          echo "ECR_URI=$ECR_URI" >> $GITHUB_ENV
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply (deploy ECS)
        run: terraform apply -auto-approve \
              -var="ecr_uri=${ECR_URI}" \
              -var="image_tag=${IMAGE_TAG}"
